### ISSUE TITLE
is support on windows?

### ISSUE THREAD

**Issue by hmfms** [foyer-rs/foyer#263]
error[E0432]: unresolved import `std::os::fd`
  --> E:\rust\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\foyer-storage-0.3.0\src\device\fs.rs:17:9
   |
17 |     os::fd::{AsRawFd, BorrowedFd, RawFd},
   |         ^^ could not find `fd` in `os`

**Comment by MrCroxx** [comment]
Hi @hmfms , *foyer* is aimed to support both unix-like system and windows. But it is still under development now. So the support on Windows may not be fullfilled now. 

Let me mark this issue as a bug, and I'll fix it later.

**Comment by hmfms** [comment]
recently , I want test it on Windows , Do you have a schedule to solve it ?

**Comment by MrCroxx** [comment]
> recently , I want test it on Windows , Do you have a schedule to solve it ?

Sorry, @hmfms . I cannot give a fixed schedule for it now. Currently, I'm working on the in-memory cache component of foyer, which is also part of my task of my full-time job. Plus, I don't have a windows environment now.

I'll fix the issue after the in-memory cache is merged. (And it will happen soon for I've finish the PR, test and received approves, FYI #270 and related PRs). I'll setup a windows environment with my PVE to fix the bug on Windows.

**Comment by MrCroxx** [comment]
And I think I need to setup a CI pipline on Windows and MacOS. Let me open an issue to track.

**Comment by MrCroxx** [comment]
Hi, @hmfms . Now I'm investigating the build on Windows with my PVE. I've not been developed on a Windows machine for years and never write Rust on Windows. May I know what's your setup of your Rust environment and how I like to develop with foyer?
