### ISSUE TITLE
Can't get the metrics info by metrics_prometheus crate

### ISSUE THREAD

**Issue by Ma1oneZhang** [foyer-rs/foyer#688]
I used to register the foyer crate metrics into my own prometheus registry like belowing code
```rust
metrics_prometheus::install();
// do something
```
But after the version update(0.10.1 => 0.11.1), i can't use it to access th metrics in foyer crate anymore.

How can i solve the problem?

**Comment by Ma1oneZhang** [comment]
I'm using default registry, i just repair some update changes and not working anymore.

**Comment by MrCroxx** [comment]
And the version of metrics and metrics-prometheus?

FYI: https://github.com/instrumentisto/metrics-prometheus-rs/issues/10

**Comment by MrCroxx** [comment]
Verified with @Ma1oneZhang offline. This is caused by they are using wrong registry. Close.
