### ISSUE TITLE
perf: performance regression on RisingWave with 0.11

### ISSUE THREAD

**Issue by MrCroxx** [foyer-rs/foyer#708]
There is an obvious regression on nexmark Q7 and Q014 for RisingWave with foyer 0.11 rather than with foyer 0.10.

<img width="1863" alt="image" src="https://github.com/user-attachments/assets/d74ceeda-09eb-443e-b717-86e57a1029b1">

Based on the flamegraph, the regression comes from 3 stacks:

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/8d8dcb3c-91f4-4adf-8fba-8908ee1e51ba">

Which are:

<img width="925" alt="image" src="https://github.com/user-attachments/assets/c096e02a-034f-4e05-ba04-cc06da435a76">

and

<img width="927" alt="image" src="https://github.com/user-attachments/assets/fde49e0a-c91a-4857-ad7d-21356521fcba">

and

<img width="924" alt="image" src="https://github.com/user-attachments/assets/1cb729d1-6604-45bb-8ae2-bf5b7034979f">

Let's see why.

Full flamegraphs:

![rw 010](https://github.com/user-attachments/assets/21b0ae1b-e60a-4808-9f36-7f5976e82ac9)

![rw 011](https://github.com/user-attachments/assets/e20e57fa-4c9f-4c0a-a61a-dc3d3bb0c13d)

Grafana:

010: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=cdtasocg64074c&var-namespace=xx-foyer-010-1&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1726042331594&to=1726086587137
011: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=cdtasocg64074c&var-namespace=xx-foyer-011-1&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1726041953341&to=1726086965390

**Comment by MrCroxx** [comment]
<img width="452" alt="image" src="https://github.com/user-attachments/assets/003ee8c1-dd95-4b3f-9767-931ba529bf0b">

**Comment by MrCroxx** [comment]
<img width="448" alt="image" src="https://github.com/user-attachments/assets/5d55d349-8398-44f8-99d9-4640ceb6c211">

**Comment by MrCroxx** [comment]
<img width="465" alt="image" src="https://github.com/user-attachments/assets/66941993-7b3b-4aa9-b8f1-e7538a1bbde1">

**Comment by MrCroxx** [comment]
Seems the memory buffer overhead in foyer 0.11 caused heavier operator memory eviction in RW.

**Comment by Li0k** [comment]
> Seems the memory buffer overhead in foyer 0.11 caused heavier operator memory eviction in RW.

Can you share the memory consumption metrics from the foyer side ?

**Comment by MrCroxx** [comment]
> > Seems the memory buffer overhead in foyer 0.11 caused heavier operator memory eviction in RW.
> 
> Can you share the memory consumption metrics from the foyer side ?

Actually, I don't think there is a metrics showing it. It is caused by a temporary buffer that was introduced in 0.11. I'm trying to remove it when there is no compression needs.

**Comment by MrCroxx** [comment]
Solved. The regression is caused by the misleading argument `buffer_threshold` in v0.11. I'll rename it.
