### ISSUE TITLE
request: please open the wiki editing permission

### ISSUE THREAD

**Issue by ssfdust** [foyer-rs/foyer#819]
as title

**Comment by MrCroxx** [comment]
Hi, @ssfdust . Thanks for asking. However, foyer is not using github wiki. It is using a dedicated repo to manage documents with [Docusaurus](https://docusaurus.io) in https://github.com/foyer-rs/website . PR is acceptable there. 🙌

Thank you very much for your contribution. 🥰

**Comment by ssfdust** [comment]
Got it.
